app = 'spotify-true-random'
primary_region = 'ewr'

[env]
SITE_URL = "https://spotify-true-random.tomeraberba.ch"

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
